### ISSUE TITLE
How to remove all elements with css class/id contains a specified string?

### ISSUE THREAD

**Issue by sergiotapia** [philss/floki#135]
I have a bunch of `filter_out` calls to specific variations of footers, for example:

```
|> Floki.filter_out(".footer")
|> Floki.filter_out(".post__footer")
|> Floki.filter_out(".post-footer")
etc
```

The problem is that I can't guess all the footer classes and IDs online. It's impossible. Is there a way for me to remove all elements where the class or id contains footer anywhere?

It would remove:

```
<div id="footer">
<div id="expanded-footer">
<div class="side-footer">
<div class="example js-highlight footer">
```

Appreciate any assistance!

**Comment by philss** [comment]
Hi @sergiotapia!

You can use the "contains" attribute selector from CSS3. Example:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
  </head>
  <body>
    <h1>A title</h1>
    <div class="some-footer">Me, a footer</div>
    <div class="some-content">Content</div>
    <footer>
      Also, a footer
    </footer>
    <div id="the-footer">Definetely, the footer</div>
  </body>
</html>
```

And with Floki:

```elixir
Floki.filter_out(html, "[class*=footer], footer, [id*=footer]")
```

This will remove all elements that has classes or ids containing "footer" in the name, and also `footer` elements.

Note that `Floki.filter_out/2` only accepts complex selectors since version [0.13.0](https://github.com/philss/floki/blob/master/CHANGELOG.md#0130---2017-01-22).

**Comment by sergiotapia** [comment]
Works terrific! Thank you @philss

**Comment by philss** [comment]
Awesome, @sergiotapia!
