### ISSUE TITLE
When 2 tags with only a space between them, space is removed

### ISSUE THREAD

**Issue by leighhalliday** [philss/floki#14]
Example html:
&lt;p&gt;I want &lt;a href="http://www.google.com">link to&lt;/a&gt; &lt;strong&gt;article&lt;/strong&gt;&lt;/p&gt;

When run through floki:
  [{"p", [],
    ["I want ", {"a", [{"href", "http://www.google.com"}], ["link to"]},
     {"strong", [], ["article"]}]}]}]

Maybe this is the intended result... which is perfectly fine. I was hoping to use floki for a weird use-case... basically run HTML through floki, parse through the floki response, removing tags/attributes that aren't allowed, and then re-create html. Essentially using floki to help me cleanse user inputted html to remove tags that aren't allowed and/or malicious javascript attributes (xss attacks).

Because of how I wanted to use it, the space between &lt;/a&gt; and &lt;strong&gt; is actually important, otherwise "link to" and "article" will be touching each other.

Feel free to close the issue if it was intended.

**Comment by philss** [comment]
Hi @leighhalliday, great to know that your are using Floki! :)

This is an important issue, but it's not easy to solve. I'm using the [`mochiweb`](https://github.com/mochi/mochiweb) lib which is the responsible for parsing HTML inside Floki, so the problem is in that library. It's a great parser, but has some issues like this. Unfortunally I don't have much control over the parser.

I'm planning to write and release a complete new HTML parser in Elixir in some point of this year. But for now I can't help you :/.

I'm closing the issue for now, but I will revisit in the future when I have that parser.
Thanks!
