### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by tomciopp** [philss/floki#178]
There is no option to disable logging, while it is helpful to see that a character is being ignored it just adds noise when in test or production.

**Comment by philss** [comment]
I've being thinking on this feature and actually I think we can reduce the level of logging from `warn` to `info` or `debug` instead of configuring to log or not. What do you think?

Also I plan to change the interface a little bit on this matter. I think a parsing error on a selector should result in an error. This particular change can wait for feature versions, specially if/when we have an `Either` as return instead of `List` that we have today.

**Comment by philss** [comment]
Closing in favor of #192.
