### ISSUE TITLE
update dom elements

### ISSUE THREAD

**Issue by cj** [philss/floki#2]
Is it possible to update the dom elements?

**Comment by brweber2** [comment]
```elixir
    html = """
        <div>
            <span>hello</span>
        </div>
    """
    Floki.parse(html)
    |> Floki.transform("span", fn element -> {"div", [], ["goodbye"]} end )
    #
    # <div>
    #     <div>goodbye</div>
    # </div>
    # 
```
Rather than just find the elements that match and return them as a list, it would use the original parsed HTML data structure as the accumulator and apply the callback function to replace each match. 
The implementation would be very similar to find only it would have an additional argument (the callback function) and the accumulator would be the entire HTML document and not just the list of matches. 
Is something like this possible today?

**Comment by philss** [comment]
@brweber2 Thanks for the proposal.

Yes, this is possible. I think for this feature we need something more flexible, like a "protocol" for saying that we want to "add" attributes, or change the tag name (type), or "push" a new child into the tree. 

Something like:

```
Floki.transform(html_tree, "span", fn element -> {:add_child, "a text"} end)
# or
Floki.transform(html_tree, "span", fn element -> {:replace_type, "div"} end)
# or
Floki.transform(html_tree, "span", fn element -> {:add_attribute, {"class", "farawell"}} end)
```

What do you think?

**Comment by philss** [comment]
Since there was not much discussion here I'm closing this issue.
Please open another issue to keep the discussion if needed. Thanks!
