### ISSUE TITLE
Children/content manipulation support

### ISSUE THREAD

**Issue by chengyin** [philss/floki#206]
Currently we can manipulate tag name and attributes with `Floki.map/2`, what about the children/content?

Use case is to override certain elements:
- Input: `<img src="nonfound.jpg" alt="picture" />` 
- Output: `<div>picture</div>`

**Comment by philss** [comment]
@chengyin I'm sorry for the delay.
I think you can't do this right now for the same reason I explain in #207.
I'm going to investigate more how can this be done.

**Comment by chengyin** [comment]
Thanks Philip, no need to be sorry about the delay. We use floki in production and thank you for the work you've already done.

**Comment by ericlathrop** [comment]
I wanted to solve this same issue, and I wrote my own version of `map` that supported manipulation of child elements:

```elixir
  def map(text, _fun) when is_binary(text), do: text

  def map([head | tail], fun) do
    case map(head, fun) do
      nil -> map(tail, fun)
      mapped_head -> [mapped_head | map(tail, fun)]
    end
  end

  def map([], _fun), do: []

  def map({elem, attrs, children}, fun) do
    mapped_children = map(children, fun)
    fun.({elem, attrs, mapped_children})
  end
```

Example of removing a child element from parent:
```elixir
iex(9)> "<div><strong>hello</strong><p>world</p></div>" |> Floki.parse() |> MyModule.map(fn {
"div", _, _} -> {"a", [{"class","myClass"}], []}; other -> other end) |> Floki.raw_html()
"<a class=\"myClass\"></a>"
```

Example of element removing itself by returning `nil`:
```elixir
iex(14)> "<div><strong>hello</strong><p>world</p></div>" |> Floki.parse() |> MyModule.map(fn {"p", _, _} -> nil; other -> other end) |> Floki.raw_html()                               
"<div><strong>hello</strong></div>"
```

Example of element replacing children:
```elixir
iex(20)>   "<div><strong>hello</strong><p>world</p></div>" |> Floki.parse() |> MyModule.map(fn {"strong", attrs, _} -> {"strong", attrs, [{"span", [], ["greetings"]}]}; other -> other end) |> Floki.raw_html()
"<div><strong><span>greetings</span></strong><p>world</p></div>"
```

I think it makes sense to replace `Floki.map/2` with this implementation, but it would be a breaking change because the `fun` arg is now required to accept a tuple of size 3 instead of size 2 to support child elements.

Would you accept a PR for this change? Do you want to replace `Floki.map/2` with this or would you like to add it with a new name to avoid the breaking change?

**Comment by philss** [comment]
@ericlathrop Thank you for the suggestion! I started to think that the name of this function should not be `map`, since it does not work as the conventional mapping of lists.

Maybe we can name it `traverse_and_update`, or something similar. Maybe we can deprecate the current `map` .
What do you think?

**Comment by ericlathrop** [comment]
I think `map` is a decent name because it maps the input tree to a new tree. On the other hand, I like picking a new name to avoid the breaking change. I'll put together a PR with `traverse_and_update`, and you can change the name if you want.

**Comment by philss** [comment]
@ericlathrop OK, go for it. Thank you!

**Comment by philss** [comment]
@ericlathrop Thank you for this PR. I'm thinking of soft deprecate the `Floki.map/2` after this. I think `traverse_and_update` is a better name because it is explicit on its intentions.

**Comment by philss** [comment]
@chengyin this is now supported by the function `Floki.traverse_and_update/2`. Please check that function.

@ericlathrop And thank you very much for solving the issue! :purple_heart:
