### ISSUE TITLE
parse_document != (deprecated) parse

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [philss/floki#244]
It looks like the new `parse_document`'s output is not the same as the deprecated `parse`. By using the example provided in the documentation:

```
html = """
  <html>
  <body>
    <div class="example"></div>
  </body>
  </html>
"""
Floki.parse_document(html)
{:ok,
 [
   {"html", [],
    [
      {"head", [], []},
      {"body", [],
       [
         "\n",
         "    ",
         {"div", [{"class", "example"}], []},
         "\n",
         "  ",
         "\n",
         "  ", 
         "\n"
       ]}
    ]}
 ]}
```

The expected output is the one provided in the documentation: 

```
{:ok, [{"html", [], [{"body", [], [{"div", [{"class", "example"}], []}]}]}]}
```

This issue might be related with #236 

Presently, this issue breaks my code: should start fixing it or it's not an intended behavior and will be corrected?

Thanks

**Comment by philss** [comment]
Hi @alessandrousseglioviretta! 

This is indeed related with #236, and it is a difference of how the parses work. It is strange that you didn't have this difference before, because `parse/1` configured with another parse was returning the three according to the parser configured.

Can you check if you configured correctly the other parser (probably html5ever) with the previous version?

**Comment by alessandrousseglioviretta** [comment]
yes, I was using html5ever, configured as as it is explained in the Floki documentation: how should I proceed?

**Comment by philss** [comment]
@alessandrousseglioviretta yes, it seems that for some reason the parser in use was the MochiWeb parser, which is the default one. I'm closing this issue because it is kind of duplicated with #236, OK?
