### ISSUE TITLE
Dialyzer reports warning on valid code.

### ISSUE THREAD

**Issue by Devon-Olivier** [philss/floki#269]
## Description

Using code example in Floki's documentation generates the following warning from Dialyzer:
`
[ElixirLS Dialyzer] [W] The call 'Elixir.Floki':filter_out
         ({<<100,105,118>>,
            [],
            [{<<115,99,114,105,112,116>>, [], [<<104,101,108,108,111>>]},
             <<32,119,111,114,108,100>>]},
           <<115,99,114,105,112,116>>) breaks the contract
           (binary() | html_tree(), 'Elixir.Floki.FilterOut':selector()) ->
              [any()]
`

## To Reproduce

- Using Floki v0.26.0
- Using Elixir v1.10.1
- Using Erlang OTP v22.x.x
- With this code:
  ```elixir
  # An example to reproduce the problem
  Floki.filter_out({"div", [], [{"script", [], ["hello"]}, " world"]}, "script")
  ```

## Expected behavior

No warnings given by Dialyzer.

**Comment by philss** [comment]
@Devon-Olivier this is correct, because `Floki.filter_out/2` expects a `Floki.html_tree()`, which is a list of `Floki.html_tag()` as you can see in [https://hexdocs.pm/floki/Floki.html#t:html_tree/0](https://hexdocs.pm/floki/Floki.html#t:html_tree/0).
I think the fix here is to accept `Floki.html_tag()` too.
