### ISSUE TITLE
DOM tree to HTML

### ISSUE THREAD

**Issue by glaucocustodio** [philss/floki#32]
Hi guys, if I do `Floki.find(html, "#wrapper")` for instance I very likely will get a lot of sub DOM elements, can't I convert it to HTML? I just saw `Floki.text`, but I dont want just text.

Something like:
`Floki.find(html, "#wrapper") |> Floki.raw_html`
Result:
`<div id="wrapper">... children DOM here ...</div>`

**Comment by philss** [comment]
@glaucocustodio this functionality does not exist **yet**. But I'm considering add it.

The main problem today is that `mochiweb`, which is the lib that really does the parsing of HTML, does not consider some spaces as text nodes. This problem was reported in this issue: https://github.com/philss/floki/issues/14

So, the resultant HTML would be different from the original one.

**Comment by glaucocustodio** [comment]
I've added this functionality, please check https://github.com/philss/floki/pull/33. Let me know if it's all ok.

**Comment by philss** [comment]
Closed by https://github.com/philss/floki/pull/33

Thanks @glaucocustodio!

**Comment by philss** [comment]
@glaucocustodio Version 0.6 released with this new feature. Enjoy! :)

**Comment by glaucocustodio** [comment]
Great! Thanks.
