### ISSUE TITLE
Deprecation warnings using IO.warn ignore log levels and are not idiomatic

### ISSUE THREAD

**Issue by juulSme** [philss/floki#329]
We get deprecation warnings in our production system logs because Floki uses IO.warn to spam these warnings. This is not helpful because:
- the messages are not formatted by Elixir's logger, breaking our logging tools
- the messages are output at runtime, not compile time when the dev could do something about them
- the messages are repeated every time the function is called, which is overkill
- the messages cannot be silenced by using log levels

The deprecation warnings should be generated using `@deprecated` tags, as per Elixir standards: https://elixir-lang.org/blog/2018/01/17/elixir-v1-6-0-released/

**Comment by philss** [comment]
@juulSme I think you are correct in most of the points! Thank you for bringing the issue! :purple_heart: 
I did add the `IO.warn` calls inside some functions because some versions of it are accepting binaries in order to parse inside the function. This is, AFAIK, not possible to detect in compile time (unless by some tools like dialyzer).

This behavior is deprecated, but we shouldn't be using `IO.warn`.  I think changing it to use `Logger` is desired and it's what I'm going to do for now.

**Comment by juulSme** [comment]
No problem :) I did try to fork the lib and solve the issue using `@deprecated` tags but it's not that simple because you can only deprecate a `function/n` (specific arity of a function) in its entirety, not a single pattern match within an arity. So in order to use `@deprecated` you would have to create functions with different names for the behavior you want to keep, or maybe a new module with the same function names (and deprecate the entire old module). This would allow you to use Elixir's built-in deprecation features, so maybe this would be a good alternative solution?

**Comment by philss** [comment]
@juulSme yeah, this is not trivial because of that: specific clauses are deprecated, but not the entire function.
I don't like the idea of create another module or rename the functions because the whole idea is to remove them soon. It seems like I'm trying to keep them for logger :sweat_smile: 

I will change the `IO.warn` for a `Logger.info`, ok?
