### ISSUE TITLE
Remove embedded mochiweb code

### ISSUE THREAD

**Issue by philss** [philss/floki#5]
This is low priority.

The idea is to remove [mochiweb](https://github.com/mochi/mochiweb) code from this codebase.

Solutions are:
- use a hex package of mochiweb (current not available);
- create a new HTML parser in Elixir and use as hex dependency.

**Comment by os6sense** [comment]
Might another solution be a hex community package? https://github.com/hexpm/community

**Comment by philss** [comment]
@os6sense Great idea! I didn't know about that! I will try the hex community approach. Thanks!

**Comment by philss** [comment]
@os6sense Thanks for the suggestion! The package is now published and the floki v0.1.1 is already using it.

**Comment by sntran** [comment]
Sorry to bring back an old issue, but is there a reason that we need the whole `mochiweb` package? Looks like you only uses the HTML parser from `mochiweb`, and that module has only seen 1 commit (which was to update the license) since 2013.

Would it be simpler to just include that module in the codebase?

Or, write own parser.

**Comment by philss** [comment]
Hi @sntran,

Your question is valid. I moved out the whole `mochiweb` code because I didn't want to maintain that code in this repository. The main reason is because I don't know Erlang enough to understand what is going on inside that code. Or perhaps I don't know the mechanics of the HTML parser enough.

So that lead to your second suggestion, which is write my own parser: I really want to do this, but this will take some time. I think it will be alive before `Floki` reaches `1.0`.
