### ISSUE TITLE
Commented out html do not show up in find function

### ISSUE THREAD

**Issue by ollaollu** [philss/floki#70]
Floki is not finding elements in comments. 

I have this `src` I fetched with `Hound` and I passed it to `Floki.find(src, "span")`. Floki only returns the `span` with the `class='visible'` like this `[{"span", [{"class", "visible"}], [" hello "]}]`. The commented out span is totally neglected.

Source:

```
<div class='parent'>
  <div class='child'>
    <span class='visible'> hello </span>
    <!-- <span class='commented'> hi </span> -->
  </div>
</div>
```

Is there a way to fetch commented out code? Or there's a temporary hack I can use?

You can reproduce this with:

```
Floki.find("<div class='parent'><div class='child'><span class='visible'> hello </span><!-- <span class='commented'> hi </span> --></div></div>", "span")
```

**Comment by philss** [comment]
Hi @ollaollu, thanks for open the issue.
 
This is not supposed to work because the code between comments is not interpreted as HTML.
It is just a string that is ignored in the process of finding HTML nodes.

You can do a hack that is: before parsing the document, replace the `<!--` and `-->` tokens by a personalized HTML tag.

Example:

```elixir
"""
<div class='parent'>
  <div class='child'>
    <span class='visible'> hello </span>
    <!-- <span class='commented'> hi </span> -->
  </div>
</div>
"""
|> String.replace("<!--", "<my-comment>")
|> String.replace("-->", "</my-comment>")
|> Floki.find("span")
```

Just be aware that this my cause collateral effects. Maybe you want to replace only some parts of the document. For that you need a more complex regex, or use Floki to find the parent and do a "Floki.raw_html/1" on it.

I'm gonna close this one. Feel free to ping me again if needed. Thanks!
