### ISSUE TITLE
Cannot find og: tags with Floki.find/2

### ISSUE THREAD

**Issue by jonzlin95** [philss/floki#80]
```
html = """<html>
    <head>
      <title>Tag title - test</title>
      <meta property='og:image' content='http://i.imgur.com/qQNJVAY.png'>
      <meta property='twitter:image' content='http://i.imgur.com/O40KSbh.png'>
    </head>

  </html>
  """

Floki.find(html, "meta[property=og:image]")
[warn] Unknown token {:unknown, 1, ':'}. Ignoring.
[]
```

Hi. Basically I can't seem to use Floki.find/2 to get any properties with : in them (opengraph, twitter etc.) This bug seems to have popped up after v0.9.0. The above code works on 0.9.X, but breaks starting on 0.10.X

Thanks!

**Comment by philss** [comment]
Hi @jonzlin95!

You are right: the behavior changed a little bit after v0.10.0. The reason is that we were using the `:` character in a wrong way. This char should be used only for pseudo-class selectors or inside quotes.

For your code to work you need to use single quotes like this:

```elixir
Floki.find(html, "meta[property='og:image']")
```
or scape the double quotes:

```elixir
Floki.find(html, "meta[property=\"og:image\"]")
```

I'm gonna close the issue. Feel free to open again if you have any questions.

Thanks!

**Comment by jonzlin95** [comment]
Thanks a lot for the quick reply mate! Would be happy to help with some PR's for documentation, let me know if you need some help.

Also thanks a lot for the great work.

**Comment by philss** [comment]
@jonzlin95 thanks! 😃 

Good to know that! I can't think of docs to write right now. But I will let you know and ask your help when needed. Fell free to suggest docs or changes too.
